### ISSUE TITLE
Unsafe HTTPS use

### ISSUE THREAD

**Issue by wolfmd** [frostwire/frostwire-android#173]
Running a security scan against the source code of this project has shown that the HTTPS used in this application has been manually overiden. Using HTTPS increases the security of credentials transmitted between the device and server as well as guaranteeing there is no middle-man attacker feeding malicious data to the user. Guides to properly implementing HTTPS can be found here: https://developer.android.com/training/articles/security-ssl.html

/rostwireandroid/src/core/com/frostwire/android/core/HttpFetcher.java:384:	AllowAllHostnameVerifier used, this is not a secure connection

**Comment by aldenml** [comment]
I will close this since in the future we will use other http framework,
