### ISSUE TITLE
Need to change the promotions view.

### ISSUE THREAD

**Issue by amit2409** [frostwire/frostwire-android#193]
![changes made to searchfragment](https://cloud.githubusercontent.com/assets/10769536/6210308/3ed4d0fe-b5f4-11e4-85f1-3e4d45cc080d.png)
![changes made to slide](https://cloud.githubusercontent.com/assets/10769536/6210309/3ed6d66a-b5f4-11e4-9662-2b4ea3831519.png)

I want to fetch objects from http://music-torrent.net/ using jsoup library on the homescreen of the app but I'm unable to do that. I'm able to extract the image url's and titles from http://music-torrent.net/ .

I made changes to only two classes
•	com.frostwire.android.gui.fragments.SearchFragment
•	com.frostwire.frostclick.Slide

**Comment by gubatron** [comment]
The files shown on the app home screen have to be licensed under Creative Commons or some sort of Public Domain copyright license. The content shown there is controlled by FrostWire's editorial team and the content is prepared and served via update.frostwire.com.

Are you a representative of Music-Torrent.net? This integration is done outside the client code and it serves both FrostWire for Android and FrostWire for Desktop.

**Comment by gubatron** [comment]
there's also of course the possibility that you're doing this for a FrostWire fork, in that case you're free to hack away as you please.

**Comment by amit2409** [comment]
Thanks for your reply sir.

It is part of my university project. I will eventually put cc work here. I gave music-torrent.net as an example.

**Comment by gubatron** [comment]
What you want to do is actually a lot easier, and you won't need to hack the android app code, except for one line.

Go to [Constants.java](https://github.com/frostwire/frostwire-android/blob/master/src/core/com/frostwire/android/core/Constants.java#L157) 

On the line I've linked to there's a constant called `SERVER_PROMOTIONS_URL`

Our app points to a service that delivers the promoted free downloads:
http://update.frostwire.com/o.php

This service is supposed to give out JSON output representing the slide objects, FrostWire for desktop uses an even better JSON at http://update.frostwire.com/o2.php

The JSON you want to play with looks like this:
```json
{
    "slides": [
        {
            "imageSrc": "http://static.frostwire.com/images/overlays/toussaint_morrison_dr_wylie_edo_overlay.jpg",
            "url": "http://www.frostclick.com/wp/index.php/2014/12/24/toussaint-morrison-dr-wylie-edo/",
            "duration": 240000,
            "title": "Toussaint Morrison and Dr Wylie's Edo",
            "size": 151503983,
            "method": 0,
            "torrent": "http://dl.frostwire.com/torrents/audio/music/Toussaint_Morrison_Dr_Wylie_Edo_MP3_FrostClick_FrostWire_DEC_24_2014.torrent"
        },
        {
            "imageSrc": "http://static.frostwire.com/images/overlays/internets_own_boy_aaron_swartz_documentary_1.jpg",
            "url": "http://www.frostclick.com/wp/index.php/2014/07/22/the-internets-own-boy-the-story-of-aaron-swartz/",
            "duration": 240000,
            "title": "The Internet's Own Boy",
            "size": 1572024213,
            "method": 0,
            "torrent": "http://dl.frostwire.com/torrents/video/The_Internets_Own_Boy_The_Story_of_Aaron_Swartz_HD_FROSTWIRE_JULY_21_2014.torrent"
        },
        {
            "imageSrc": "http://static.frostwire.com/images/overlays/reset_overlay.jpg",
            "url": "http://www.frostclick.com/wp/index.php/2014/06/27/reset-resynthformation-2/",
            "duration": 240000,
            "title": "Re:Set - Resynthformation",
            "size": 55968564,
            "method": 0,
            "torrent": "http://dl.frostwire.com/torrents/audio/music/ReSet_Resynthformation_SOSEP051_FrostClick_FrostWire_6_28_2014.torrent"
        },
        {
            "imageSrc": "http://static.frostwire.com/images/overlays/mixtape_volume_4_overlay.jpg",
            "url": "http://www.frostclick.com/wp/index.php/2013/12/30/frostwire-creative-commons-mixtape-vol-4/",
            "duration": 240000,
            "title": "FrostWire Creative Commons Mixtape Volume 4",
            "size": 89239639,
            "method": 0,
            "torrent": "http://dl.frostwire.com/torrents/audio/music/FrostWire_Creative_Commons_Mixtape_Volume_4__12_30_2013.torrent"
        }
    ],
    "randomStart": false
}
```

**Comment by amit2409** [comment]
Thanks

**Comment by amit2409** [comment]
But I knew that already. My question was on jsoup parsing of HTML. BTW I'm able to solve the problem.

**Comment by gubatron** [comment]
afaik we don't have a jsoup library, do we?
(your code seems like it would work, I've seen similar libraries that parse XML out of selector-like apis)
