### ISSUE TITLE
./res/values-zh/strings.xml - Chinese translation update needed (71% translated only)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-android#213]
Missing elements:

```xml
<string name="activity_mediaplayer_name">Media Player</string>
<string name="wifi_sharing_settings">Wi-Fi Sharing Settings</string>
<string name="torrent_max_peers">Max Peers</string>
<string name="clear_search_cache">Clear search cache</string>
<string name="drawer_close">Close navigation drawer</string>
<string name="saving_to_internal_memory_description">You also have an SD card (%1$s available)</string>
<string name="bittorrent">BitTorrent</string>
<string name="add_transfer_label">Paste a magnet or torrent URL</string>
<string name="drawer_open">Open navigation drawer</string>
<string name="use_torlock">Use TorLock</string>
<string name="use_monova">Use Monova</string>
<string name="upnp_discovery_summary">Share files with peers on the local Wi-Fi network.</string>
<string name="delete_this_track">Delete this track</string>
<string name="five_dollars">$5</string>
<string name="transfer_status_demuxing">Demuxing</string>
<string name="app_shutdown_dlg_message">This will shutdown all transfers and background services. Are you sure?</string>
<string name="ten_dollars">$10</string>
<string name="one_file_shared">One file has been shared to FrostWire devices on the same Wi-Fi network.</string>
<string name="saving_to_internal_memory">Saving to Internal Memory</string>
<string name="dialog_desktop_upload_request_text_text">%1$s wants to send you %2$s totalling %3$s</string>
<string name="dummy_author">[Author]</string>
<string name="my_filetype">My %s</string>
<string name="accept">Accept</string>
<string name="paused">Paused</string>
<string name="retry_search">Retry</string>
<string name="android_will_erase_files_if_frostwire_is_uninstalled">Android will erase downloaded files if FrostWire is uninstalled.</string>
<string name="use_eztv">Use Eztv</string>
<string name="reject">Reject</string>
<string name="desktop_transfer_status_unknown">Unknown</string>
<string name="device_memory">Device\'s Memory</string>
<string name="please_check_connection_status_before_resuming_download">Please check the status of your internet connection before resuming.</string>
<string name="youtube_download_status_verifying">Verifying</string>
<string name="block">Block</string>
<string name="cloud_downloads_coming">Sorry: Starting cloud downloads from here will be available on further updates.</string>
<string name="menu_space_shortcut_label">Space</string>
<string name="donate_10">Donate $10</string>
<string name="confirm_download">Confirm Download</string>
<string name="sdcard_storage">SD\'s Storage</string>
<string name="deleted_crawl_cache">Deleted crawl cache</string>
<string name="are_you_sure_you_want_to_download_the_following">Are you sure you want to download the following %1$s (%2$s)?</string>
<string name="donate_25">Donate $25</string>
<string name="player_paused_press_and_hold_to_stop">Player paused. (Tip: Press and hold to stop)</string>
<string name="menu_delete_shortcut_label">Del</string>
<string name="magnet_url_added">Magnet URL added to transfers. (Magnets work best on Wi-Fi)</string>
<string name="use_monova_summary">Monova is magnet based, works only on Wi-Fi</string>
<string name="or_enter_url">or enter URL</string>
<string name="http_download_status_uncompressing">Uncompressing</string>
<string name="use_youtube">Use YouTube.com</string>
<string name="transfers_select_completed">completed</string>
<string name="upnp_discovery">Wi-Fi Sharing</string>
<string name="transfers_context_menu_pause_stop_all_transfers">Pause/Stop all transfers</string>
<string name="use_kat_summary">KAT is magnet based, works only on Wi-Fi</string>
<string name="sharing_num_files">Sharing %1$s files of type %2$s</string>
<string name="wifi_sharing">Wi-Fi Sharing</string>
<string name="dialog_desktop_upload_request_title">Upload Request</string>
<string name="transfers_select_downloading">downloading</string>
<string name="free_apps">Free Apps</string>
<string name="checking_ellipsis">Checking&#8230;</string>
<string name="playlist">playlist</string>
<string name="torrent_transfer_enqueued_on_mobile_data">The torrent transfer will start downloading automatically when you connect to a Wi-Fi network.(Check your Network Settings regarding 3G/4G data usage)</string>
<string name="error_wrong_md5_hash">Error: Wrong MD5 hash</string>
<string name="error_wrong_signature">Error: Wrong signature</string>
<string name="error_no_space_left_on_device">Error: No space left to save file</string>
<string name="now_playing">Now playing</string>
<string name="use_soundcloud">Use Soundcloud.com</string>
<string name="desktop_transfer_status_complete">Complete</string>
<string name="help_translate_frostwire">Help translate FrostWire</string>
<string name="transfers_context_menu_clear_finished">Clear all finished transfers</string>
<string name="btc">BTC</string>
<string name="no_results_feedback">No results were found.\n\nCheck your internet connection or\ntry different search terms.</string>
<string name="paused_song_name">Paused %s</string>
<string name="seed">Seed</string>
<string name="you_need_a_bitcoin_wallet_app">You need a Bitcoin wallet installed on you device to submit a BTC donation.</string>
<string name="transfers_select_all">all</string>
<string name="desktop_transfer_status_cancelled">Cancelled</string>
<string name="donation_thanks">Thank you so much for Supporting FrostWire</string>
<string name="crawl_cache_size">Crawl cache %1$.2fMB</string>
<string name="wifi_sharing_disabled">Wi-fi sharing is off.\n\nWi-fi sharing can be used to share files locally between FrostWire powered devices connected to the same Wi-Fi network.\n\n&lt;a href=\"http://bit.ly/1tVReSt\"&gt;Learn more.&lt;/a&gt;</string>
<string name="pausing">Pausing</string>
<string name="prepend_shortcut_label"></string>
<string name="azureus_manager_not_created">Download can\'t be created with SD card mounted</string>
<string name="anonymous_usage_statistics_summary">Send anonymous usage statistics. No information regarding content searched, shared or played nor any information that can personally identify you will be stored on disk or sent through the network.</string>
<string name="my_music">My Music</string>
<string name="error_moving_incomplete">Error: Moving Incomplete</string>
<string name="torrent_url_added">Torrent URL added to transfers.</string>
<string name="playing_now_colon">Playing now:</string>
<string name="please_enter_valid_url">Please enter a valid URL</string>
<string name="stop">Stop</string>
<string name="watch_tv">Watch TV</string>
<string name="queued_for_checking">Queued for checking</string>
<string name="available">available</string>
<string name="are_you_sure_wifi_sharing_off">Turning off Wi-Fi sharing will make all your locally shared files unavailable to other users on the nearby Wi-Fi network.</string>
<string name="use_yify">Use Yify</string>
<string name="turn_on_wifi_sharing">Turn on Wi-fi Sharing</string>
<string name="yes_no_cancel_transfer_question_cloud">Are you sure you want to stop and remove this download from the list?</string>
<string name="desktop_transfer_status_transferring">Transferring</string>
<string name="donate">Donate</string>
<string name="torrent_transfer_consuming_mobile_data">Warning: This torrent transfer is using your 3G/4G data. (Check your Network Settings if you wish to use BitTorrent only on WiFi)</string>
<string name="transfers_context_resume_all_torrent_transfers">Resume all torrent transfers</string>
<string name="use_bitsnoop">Use BitSnoop</string>
<string name="free_download">Free Download</string>
<string name="couldnt_share_file">Could not share the file. Weird path found.</string>
<string name="storage_setting_confirm_dialog_title">SD CARD</string>
<string name="cant_resume_torrent_transfers"> "Connectivity"</string>
<string name="twenty_five_dollars">$25</string>
<string name="storage_setting_warning">WARNING: All files downloaded by FrostWire into the SD card will be deleted BY ANDROID if you uninstall FrostWire.</string>
<string name="canceling">Canceling</string>
<string name="http_download_status_save_dir_error">Save directory does not exist or can\'t be created</string>
<string name="n_files_shared">%d files has been shared to FrostWire devices on the same Wi-Fi network.</string>
<string name="install_bitcoin_wallet">Install Bitcoin Wallet</string>
<string name="http_download_status_save_dir_error">Save directory does not exist or can\'t be created</string>
<string name="n_files_shared">%d files has been shared to FrostWire devices on the same Wi-Fi network.</string>
<string name="install_bitcoin_wallet">Install Bitcoin Wallet</string>
<string name="device_storage">Device\'s Storage</string>
<string name="use_yify_summary">Yify is magnet based, works only on Wi-Fi</string>
<string name="use_archiveorg">Use Archive.org</string>
<string name="clear_search_cache_summary">Clear search cache entries</string>
<string name="file_descriptor_sd_mounted">This file was deleted from the SD card, or the SD card you have inserted is a different one.</string>
<string name="loading">Loading</string>
<string name="downloading_metadata">Downloading metadata</string>
<string name="torrent_scheme_download_not_supported">Download not supported</string>
<string name="app_shutdown_dlg_title">Shutdown</string>
<string name="are_you_sure_delete_current_track">Are you sure you want to delete the current track?</string>
<string name="block_computer">Block Computer</string>
<string name="remove_from_recent">Remove from recent</string>
<string name="bittorrent_network_summary">Connection status</string>
<string name="error_not_enough_peers">Try again, not enough peers</string>
<string name="menu_enter_shortcut_label">Enter</string>
<string name="track">track</string>
<string name="file_descriptor_sd_unmounted">This file belongs to an SD card, please insert it on your device.</string>
<string name="donate_in_btc">Donate in bitcoins</string>
<string name="torrent_transfer_paused_disconnected_from_bittorrent">The transfer has been paused because you are Disconnected. (Check your BitTorrent connection in Settings)</string>
<string name="free_sponsored_app">Free Sponsored App</string>
<string name="support">Support</string>
<string name="donate_1">Donate $1</string>
<string name="donate_5">Donate $5</string>
<string name="use_frostclick">Use FrostClick</string>
<string name="one_dollar">$1</string>
<string name="storage_setting_confirm_dialog_text">I understand that all files downloaded to the SD Card by FrostWire will be deleted BY ANDROID the moment the FrostWire application is uninstalled from this device and I will not hold FrostWire LLC liable for any files lost.</string>
<string name="cant_open_file_does_not_exist">I can\'t open %1$s, the file does not exist.</string>
<string name="anonymous_usage_statistics">Anonymous Usage Statistics</string>
<string name="saving_to_sd_card">Saving to SD card.</string>
<string name="torrent_max_peers_summary">Max Peers</string>
<string name="transfers_context_menu_stop_delete_data">Stop and delete data</string>
<string name="use_btjunkie">Use BTJunkie</string>
<string name="use_tpb_summary">TPB is magnet based, works only on Wi-Fi</string>
```

**Comment by ooilee** [comment]
<string name="activity_mediaplayer_name">媒體播放器</string>
<string name="wifi_sharing_settings">Wi-Fi 共享設置</string>
<string name="torrent_max_peers">最大連接數</string>
<string name="clear_search_cache">清除搜索緩存</string>
<string name="drawer_close">關閉導覽面板</string>
<string name="saving_to_internal_memory_description">您也有一張 SD 卡（%1$s 可用）</string>
<string name="bittorrent">BitTorrent</string>
<string name="add_transfer_label">貼上 Magnet（磁力）鏈接或 Torrent 鏈接</string>
<string name="drawer_open">打開導覽面板</string>
<string name="use_torlock">使用 TorLock</string>
<string name="use_monova">使用 Monova</string>
<string name="upnp_discovery_summary">和本地 Wi-Fi 網絡上的 Peer（用戶節點）共享檔案。</string>
<string name="delete_this_track">刪除此曲目</string>
<string name="five_dollars">$5 美元</string>
<string name="transfer_status_demuxing">多路抽取中</string>
<string name="app_shutdown_dlg_message">這將關閉所有傳輸和後台服務。您確定？</string>
<string name="ten_dollars">$10 美元</string>
<string name="one_file_shared">一個檔案已經分享到在同一 Wi-Fi 網絡上的 FrostWire 裝置。</string>
<string name="saving_to_internal_memory">儲存到內置記憶體</string>
<string name="dialog_desktop_upload_request_text_text">%1$s 要向您發送共計 %3$s 的 %2$s</string>
<string name="dummy_author">[創作人]</string>
<string name="my_filetype">我的%s</string>
<string name="accept">接受</string>
<string name="paused">暫停</string>
<string name="retry_search">重試</string>
<string name="android_will_erase_files_if_frostwire_is_uninstalled">如果卸載 FrostWire，Android 將會清除所下載的檔案。</string>
<string name="use_eztv">使用 Eztv</string>
<string name="reject">拒絕</string>
<string name="desktop_transfer_status_unknown">未知</string>
<string name="device_memory">裝置記憶體</string>
<string name="please_check_connection_status_before_resuming_download">請檢查網絡連接狀態再重新開始。</string>
<string name="youtube_download_status_verifying">核實</string>
<string name="block">封鎖</string>
<string name="cloud_downloads_coming">抱歉：要從這裡進行雲下載，請等候進一步產品更新。</string>
<string name="menu_space_shortcut_label">空間</string>
<string name="donate_10">捐贈 $10 美元</string>
<string name="confirm_download">確認下載</string>
<string name="sdcard_storage">SD 卡容量</string>
<string name="deleted_crawl_cache">刪除的爬行緩存</string>
<string name="are_you_sure_you_want_to_download_the_following">您確定要下載下列的 %1$s (%2$s)？</string>
<string name="donate_25">捐贈 $25 美元</string>
<string name="player_paused_press_and_hold_to_stop">播放暫停。（提示：長按以停止）</string>
<string name="menu_delete_shortcut_label">刪</string>
<string name="magnet_url_added">Magnet（磁力）鏈接已添加到傳輸。（磁力在 Wi-Fi 效果最好）</string>
<string name="use_monova_summary">Monova 基於磁力，僅適用於 Wi-Fi</string>
<string name="or_enter_url">或輸入 URL 鏈接</string>
<string name="http_download_status_uncompressing">解壓縮</string>
<string name="use_youtube">使用 YouTube.com</string>
<string name="transfers_select_completed">完成</string>
<string name="upnp_discovery">Wi-Fi 共享</string>
<string name="transfers_context_menu_pause_stop_all_transfers">暫停/停止全部傳輸</string>
<string name="use_kat_summary">KAT 基於磁力，僅適用於 Wi-Fi</string>
<string name="sharing_num_files">分享類型 %2$s 的 %1$s 個檔案</string>
<string name="wifi_sharing">Wi-Fi 共享</string>
<string name="dialog_desktop_upload_request_title">上傳請求</string>
<string name="transfers_select_downloading">下載中</string>
<string name="free_apps">免費 App</string>
<string name="checking_ellipsis">檢查&#8230;</string>
<string name="playlist">播放清單</string>
<string name="torrent_transfer_enqueued_on_mobile_data">在連接上 Wi-Fi 網絡後，Torrent 傳輸會自動開始下載。（檢查您的網絡設置，了解 3G/4G 數據使用）</string>
<string name="error_wrong_md5_hash">錯誤：MD5 雜湊 (MD5 hash) 錯誤</string>
<string name="error_wrong_signature">錯誤：簽章錯誤</string>
<string name="error_no_space_left_on_device">錯誤：無多餘空間儲存檔案</string>
<string name="now_playing">現在播放</string>
<string name="use_soundcloud">使用 Soundcloud.com</string>
<string name="desktop_transfer_status_complete">完成</string>
<string name="help_translate_frostwire">幫忙翻譯 FrostWire</string>
<string name="transfers_context_menu_clear_finished">清空完成的傳輸</string>
<string name="btc">BTC（比特幣）</string>
<string name="no_results_feedback">未找到結果。\n\n檢查網絡連接或\n嘗試不同的搜索詞。</string>
<string name="paused_song_name">暫停 %s</string>
<string name="seed">Seed（種子）</string>
<string name="you_need_a_bitcoin_wallet_app">要提交比特幣 (BTC) 捐款，貴裝置需安裝有比特幣錢包。</string>
<string name="transfers_select_all">全部</string>
<string name="desktop_transfer_status_cancelled">取消</string>
<string name="donation_thanks">多謝您支持 FrostWire</string>
<string name="crawl_cache_size">爬行緩存 %1$.2fMB</string>
<string name="wifi_sharing_disabled">Wi-Fi 共享關閉了。\n\nWi-Fi 共享可以用來在本地和連接相同 Wi-Fi 網絡，配備 FrostWire 的裝置分享檔案。\n\n&lt;a href=\"http://bit.ly/1tVReSt\"&gt;了解詳情。&lt;/a&gt;</string>
<string name="pausing">暫停</string>
<string name="prepend_shortcut_label"></string>
<string name="azureus_manager_not_created">如果裝載了 SD 卡，即不能下載。</string>
<string name="anonymous_usage_statistics_summary">發送匿名使用統計數據。所進行的內容搜索、分享或播放，以及能識別您的所有資料，都不會儲存在磁盤上，亦不會通過網絡傳送。</string>
<string name="my_music">音樂文件夾</string>
<string name="error_moving_incomplete">錯誤：移動未完成</string>
<string name="torrent_url_added">Torrent 鏈接已添加到傳輸。</string>
<string name="playing_now_colon">當前播放：</string>
<string name="please_enter_valid_url">請輸入有效的鏈接</string>
<string name="stop">停止</string>
<string name="watch_tv">看電視</string>
<string name="queued_for_checking">輪候檢查</string>
<string name="available">可用</string>
<string name="are_you_sure_wifi_sharing_off">關閉 Wi-Fi 共享將使得鄰近 Wi-Fi 網絡的其他用戶無法存取您所有的本地共享檔案。</string>
<string name="use_yify">使用 Yify</string>
<string name="turn_on_wifi_sharing">開啟 Wi-Fi 共享</string>
<string name="yes_no_cancel_transfer_question_cloud">您確定要停止此下載並將之從清單上移除？</string>
<string name="desktop_transfer_status_transferring">傳輸中</string>
<string name="donate">捐款</string>
<string name="torrent_transfer_consuming_mobile_data">警告：此 Torrent 傳輸使用您的 3G/4G 數據。（如果您只想在 WiFi 使用 BitTorrent，請檢查網絡設置）</string>
<string name="transfers_context_resume_all_torrent_transfers">恢復全部 Torrent 傳輸</string>
<string name="use_bitsnoop">使用 BitSnoop</string>
<string name="free_download">免費下載</string>
<string name="couldnt_share_file">檔案無法分享。路徑怪異。</string>
<string name="storage_setting_confirm_dialog_title">SD 卡</string>
<string name="cant_resume_torrent_transfers">「連線」</string>
<string name="twenty_five_dollars">$25 美元</string>
<string name="storage_setting_warning">警告：如果您卸載 FrostWire，通過 FrostWire 下載到 SD 卡的所有檔案將會被 ANDROID 刪除。</string>
<string name="canceling">取消中</string>
<string name="http_download_status_save_dir_error">儲存目錄不存在或無法創建</string>
<string name="n_files_shared">%d 個檔案已經分享到在相同 Wi-Fi 網絡上的 FrostWire 裝置。</string>
<string name="install_bitcoin_wallet">安裝比特幣錢包 (Bitcoin Wallet)</string>
<string name="http_download_status_save_dir_error">儲存目錄不存在或無法創建</string>
<string name="n_files_shared">%d 個檔案已經分享到在相同 Wi-Fi 網絡上的 FrostWire 裝置。</string>
<string name="install_bitcoin_wallet">安裝比特幣錢包 (Bitcoin Wallet)</string>
<string name="device_storage">裝置容量</string>
<string name="use_yify_summary">Yify 基於磁力，僅適用於 Wi-Fi</string>
<string name="use_archiveorg">使用 Archive.org</string>
<string name="clear_search_cache_summary">清除搜索緩存條目</string>
<string name="file_descriptor_sd_mounted">此檔案已經自 SD 卡刪除，抑或您插入了不同的 SD 卡。</string>
<string name="loading">加載中</string>
<string name="downloading_metadata">下載元數據</string>
<string name="torrent_scheme_download_not_supported">不支持下載</string>
<string name="app_shutdown_dlg_title">關閉</string>
<string name="are_you_sure_delete_current_track">您確定要刪除當前曲目？</string>
<string name="block_computer">封鎖電腦</string>
<string name="remove_from_recent">從最近中移除</string>
<string name="bittorrent_network_summary">連接狀態</string>
<string name="error_not_enough_peers">Peer（用戶節點）不足，請重試</string>
<string name="menu_enter_shortcut_label">輸入</string>
<string name="track">曲目</string>
<string name="file_descriptor_sd_unmounted">這個檔案為 SD 卡所有，請將卡插入裝置。</string>
<string name="donate_in_btc">用 Bitcoin（比特幣）捐款</string>
<string name="torrent_transfer_paused_disconnected_from_bittorrent">連接斷線，傳輸因此暫停。（檢查設置中的 BitTorrent 連接）</string>
<string name="free_sponsored_app">免費贊助的 App</string>
<string name="support">支持</string>
<string name="donate_1">捐贈 $1 美元</string>
<string name="donate_5">捐贈 $5 美元</string>
<string name="use_frostclick">使用 FrostClick</string>
<string name="one_dollar">$1 美元</string>
<string name="storage_setting_confirm_dialog_text">我明白，通過 FrostWire 下載到 SD 卡的所有檔案，都會在本裝置卸載 FrostWire 應用程式後被 ANDROID 刪除，而我不會就任何的檔案損失要求 FrostWire LLC 負責。</string>
<string name="cant_open_file_does_not_exist">我無法打開 %1$s。該檔案不存在。</string>
<string name="anonymous_usage_statistics">匿名使用統計數據</string>
<string name="saving_to_sd_card">儲存到 SD 卡中。</string>
<string name="torrent_max_peers_summary">最大連接數</string>
<string name="transfers_context_menu_stop_delete_data">停止並刪除數據</string>
<string name="use_btjunkie">使用 BTJunkie</string>
<string name="use_tpb_summary">TPB 基於磁力，僅適用於 Wi-Fi</string>

**Comment by gubatron** [comment]
can someone who speaks english and chinese double check this submission?
(we'll need a pull request changing the actual file in the end though)

**Comment by ooilee** [comment]
The codes gone without knowing a reason. The original file with complete codes is sent via Elance, as platform here does not support PDF or Word.

**Comment by gubatron** [comment]
@ooilee the easiest way to do this, is to clone this project using git.
Then work on the real file, commit it to a branch, and send us a Pull Request.

Then we can simply merge the changes.

**Comment by muckachina** [comment]
Don't worry @gubatron I'm on it, it was an issue copying and pasting the translation.

@ooilee I got your message, I'll send you a reply via Elance.
