### ISSUE TITLE
New Icons needed for "Send Tip/Donation" Menu Actions

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-android#217]
Now on FrostWire for Android, when we detect a torrent has payment options, the popup menu could have 2 new actions: "Send Bitcoin Tip/Donation" and "Send Donation" (fiat)

I'm not sure if there's any room for this, but it'd be nice to somehow visually differentiate ongoing transfers that support tipping, if there's space in there to put a smaller version of these icons.

**Comment by gubatron** [comment]
@marcelinkaaa  I was thinking at first of reusing the icons we have already on desktop but they're really not a good match.

Then I was thinking that a tipping hat would be perfect.

You'd have 2 similar icons, it'd be the same hat, but inside the hat you would have either a Bitcoin "B" or the dollar "$" for the fiat donations.

**Comment by marcelinkaaa** [comment]
It would be great to have the same icon on both platforms (but possibly more simplified version on android). I will look at it more closely over the weekend to see what can be done. We probably could make some space for an indication icon signaling user that they can donate to this particular torrent creator. I have made some initial layouts way back with just a little bit of alteration. Will forward soon after working on the icon.

**Comment by gubatron** [comment]
the sooner the better, we're almost ready for that release, I'll be shooting for a release candidate on monday/tuesday on android.
