### ISSUE TITLE
ERROR: specified for property 'signingConfig.storefile' does not exist

### ISSUE THREAD

**Issue by j3g** [frostwire/frostwire-android#220]
This error occurs because there is no frostwire-tools directory.
This is not mentioned in the readme.
Not sure what I should do...

in build.gradle file line 97
storeFile file("../frostwire-tools/installer_builders/android.keystore/frostwire.keystore")

**Comment by gubatron** [comment]
just do:

`./gradlew assembleDebug`

You don't need to have our signing key.
