### ISSUE TITLE
Start This Download? Pop Up Switch OK Button To right, Cancel to Left

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire-android#223]
It is customary to have the OK button on the right... I've pressed cancel quite a few times without reading when in hurry and then was wandering where are my files... 

![screenshot_2015-04-16-13-40-34](https://cloud.githubusercontent.com/assets/7243139/7191075/d75dd248-e458-11e4-9f94-9133d807d510.png)

**Comment by Andelphia88** [comment]
Stop
