### ISSUE TITLE
Torrents from BitSnoop not adding to Transfers

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire-android#279]
Tested on Samsung S4/Android 5.0.1 with no SD Card. Downloading to Internal. 
Sony Xperia Z2/ Android 5.1.1. Downloading to SD Card.
Happens only with BitSnoop only, but other sources might need more testing. Torrents from Kat, BTJunkie & TorLock did not have any issues.

When selecting a full torrent package for download, the file is marked in Search as downloaded, but does not show up in Transfers & the .torrent file does not download.
If a handpicked file from either Audio or Video from the same torrent package is marked for download, it works fine adding to Transfers and Downloading. 
Flipping screen does not help. Changing to 'Downloading' & back to 'All' does not help. Going back to Search and back to Transfers does not solve the problem either. 

Reported by multiple users as well.

**Comment by gubatron** [comment]
This githup project has been phased out.

**Comment by gubatron** [comment]
[Please leave this description on this issue](https://github.com/frostwire/frostwire/issues/42)
