### ISSUE TITLE
Update In-app Billing API v3

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire-android#84]
https://developer.android.com/google/play/billing/api.html

Google Says:
Migrate your app to In-app Billing v3 for better performance, improved stability, and new purchasing features to better meet your needs. Implementation is straightforward, and in some cases you can reduce the amount of code needed for purchases. The v3 API is also much easier to use than legacy versions - purchases are fully synchronous with results reported to your app immediately. Note that support for earlier versions of the In-app Billing API will be removed over time, so consider migrating as soon as possible.

**Comment by gubatron** [comment]
Now this has become urgent, as the current version has been discontinued and users can't donate.

**Comment by gubatron** [comment]
removed donations altogether.
